const DEFAULT_DIMENSIONS = { WIDTH: 256, HEIGHT: 256, CONTROLS_HEIGHT: 30 }
Object.freeze(DEFAULT_DIMENSIONS)
// DEFAULT_DIMENSIONS.prototype.WIDTH = 256
// DEFAULT_DIMENSIONS.prototype.HEIGHT = 256
// DEFAULT_DIMENSIONS.prototype.CONTROLS_HEIGHT = 30

export default {
    DEFAULT_DIMENSIONS
}