const DEFAULT_DIMENSIONS = { WIDTH: 256, HEIGHT: 256, CONTROLS_HEIGHT: 30 }
Object.freeze(DEFAULT_DIMENSIONS)

const DEFAULT_DIMENSIONS_SCALE = { WIDTH: 1, HEIGHT: 1 }
Object.freeze(DEFAULT_DIMENSIONS_SCALE)

export default {
    DEFAULT_DIMENSIONS, DEFAULT_DIMENSIONS_SCALE
}